-- Initial schema: users, symbols, candles, watchlist, alerts

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    created_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS symbols (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      VARCHAR(10)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    exchange    VARCHAR(255) NOT NULL,
    asset_type  VARCHAR(255) NOT NULL CHECK (asset_type IN ('STOCK', 'CRYPTO', 'FOREX')),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS candles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker        VARCHAR(20)  NOT NULL,
    interval_type VARCHAR(10)  NOT NULL,
    timestamp     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    open          NUMERIC(18,6) NOT NULL,
    high          NUMERIC(18,6) NOT NULL,
    low           NUMERIC(18,6) NOT NULL,
    close         NUMERIC(18,6) NOT NULL,
    volume        NUMERIC(38,2) NOT NULL,
    UNIQUE (ticker, interval_type, timestamp)
);

CREATE TABLE IF NOT EXISTS watchlist (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    symbol_id  BIGINT NOT NULL REFERENCES symbols(id),
    added_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    UNIQUE (user_id, symbol_id)
);

CREATE TABLE IF NOT EXISTS alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES users(id),
    ticker       VARCHAR(20)   NOT NULL,
    target_price NUMERIC(18,6) NOT NULL,
    condition    VARCHAR(255)  NOT NULL CHECK (condition IN ('ABOVE', 'BELOW')),
    status       VARCHAR(255)  NOT NULL CHECK (status IN ('ACTIVE', 'TRIGGERED', 'CANCELLED')),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    triggered_at TIMESTAMP(6) WITH TIME ZONE
);
