-- Paper Trading: trades history and current holdings

CREATE TABLE IF NOT EXISTS trades (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL REFERENCES users(id),
    ticker       VARCHAR(20)   NOT NULL,
    type         VARCHAR(255)  NOT NULL CHECK (type IN ('BUY', 'SELL')),
    quantity     NUMERIC(18,8) NOT NULL,
    price        NUMERIC(18,6) NOT NULL,
    total_amount NUMERIC(18,6) NOT NULL,
    executed_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS holdings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES users(id),
    ticker        VARCHAR(20)   NOT NULL,
    quantity      NUMERIC(18,8) NOT NULL,
    avg_buy_price NUMERIC(18,6) NOT NULL,
    UNIQUE (user_id, ticker)
);
